/*
 * This source file was generated by the Gradle 'init' task
 */
package lehmanjunitlab;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.DisplayName;

class AppTest {
    @Test
    @DisplayName("Grade 70 should return true for passing")
    void testPassingGrade() {
        LehmanGradeBook gb = new LehmanGradeBook();
        assertTrue(gb.isPassing(70), "A grade of 70 should pass.");
    }

    @Test
    @DisplayName("Grade 95 should return char 'A'")
    void testLetterGrade95(){
        LehmanGradeBook gb = new LehmanGradeBook();
        assertEquals('A', gb.getLetterGrade(95));
    }

    @Test
    @DisplayName("Grade 50 should return char 'F'")
    void testLetterGrade50(){
        LehmanGradeBook gb = new LehmanGradeBook();
        assertEquals('F', gb.getLetterGrade(50));
    }

    @Test
    @DisplayName("Grade 90 should return char 'A'")
    void testLetterGrade90(){
        LehmanGradeBook gb = new LehmanGradeBook();
        assertEquals('A', gb.getLetterGrade(90));
    }

    @Test
    @DisplayName("Grade 80 should return char 'B'")
    void testLetterGrade80(){
        LehmanGradeBook gb = new LehmanGradeBook();
        assertEquals('B', gb.getLetterGrade(80));
    }

    @Test
    @DisplayName("Grade 70 should return char 'C'")
    void testLetterGrade70(){
        LehmanGradeBook gb = new LehmanGradeBook();
        assertEquals('C', gb.getLetterGrade(70));
    }

    @Test
    void testInvalidGradeThrowsException() {
    LehmanGradeBook gb = new LehmanGradeBook();
    assertThrows(IllegalArgumentException.class, () -> {
        gb.isPassing(150);
    });
}


}
